docs(game design document): introdution part
Phoenix-Games-Revolution/last-strategy-docs pull request #23
Opened 2024-12-05 13:38 UTC by gochicus

По поводу структуры,  мне понравилось как её рекомендуют здесь:
https://sky.pro/wiki/gamedev/primer-game-design-document-gdd/

Большая часть того, что ты изложил в концепте пойдёт в раздел "Игровой процесс и механики"

2024-12-06 20:46 UTC, TorinAsakura requested changes

2024-12-06 20:46 UTC, TorinAsakura commented on docs/gdd/core/game_design_document.md
> +4. Разнообразие среды для тактических сражений:
забыл про воздух

2024-12-06 20:46 UTC, TorinAsakura commented on docs/gdd/core/game_design_document.md
> +9. Экономика, основанная на создании сложных производственных цепочек. Возможность получения ресурсов за счёт торговли и дипломатии. выстраивание торговой логистики.
после дипломатии точка, а потом с маленькой буквы

2024-12-06 20:46 UTC, TorinAsakura commented on docs/gdd/core/game_design_document.md
> +11. Внутриигровая экономическая среда, с возможностью торговли между игроками за реальные деньги с минимальной комиссии платформы.
мы реалными деньгами не можем оперировать, мы не обменник и не финансовая организация. Мы просто не запрещаем расчёты между игрокми в реальной валюте за игровые ценности. Это по сути обычный ММО рынок.

2024-12-06 20:46 UTC, TorinAsakura commented on docs/gdd/core/game_design_document.md
> +### Цели и задачи продукта
не пиши "продукта"

2024-12-06 20:46 UTC, TorinAsakura commented on docs/gdd/core/game_design_document.md
> +Цель проекта - создание постоянно развивающегося продукта, который будет постоянно давать игрокам новый опыт.
а тут вообще "проекта"

2024-12-14 10:11 UTC, TorinAsakura requested changes
Давай с этой частью закончим и в релиз её. Остальное будем делать в новых ПРах. Я уже хочу направить документ в несколько мест.

2024-12-14 10:11 UTC, TorinAsakura commented on docs/gdd/core/game_design_document.md
> +Античность: Герои древнегреческих легенд, например, царь Спарты Леонид или Александр Македонский.
тыб чо про славян бы добавил…

2024-12-14 10:11 UTC, TorinAsakura commented on docs/gdd/core/game_design_document.md
> +- Масштабные сражения: акцент на тактической гибкости и грамотном использовании конфигурации армии, выбранной на основе доступных технологий.
очень сжато, налей больше деталей

2024-12-14 10:11 UTC, TorinAsakura commented on docs/gdd/core/game_design_document.md
> +Миссии Будущего: Построены вокруг освоения космоса с возможной развилкой в сторону подводных просторов.
нет ничего про альтернативные ветви развития и выборе остановки на одной из них

2024-12-14 10:11 UTC, TorinAsakura commented on docs/gdd/core/game_design_document.md
> +3. Способности адаптироваться к особенностям карты и текущим событиям.
молю - избегай точек в элементах списка

2024-12-14 10:11 UTC, TorinAsakura commented on docs/gdd/core/game_design_document.md
> +- Строительство. Эффект: анимация строительства здания, при постройке открывается интерфейс для изучения технологий или заказа юнитов.
полагаю это лучше отделить подзаголовками иначе всё скомкается в нечитабельный вид

### Строительство
#### Эффект
- Анимация посадки
- Анимация выращивания животных
- …

2024-12-14 10:11 UTC, TorinAsakura commented on docs/gdd/core/game_design_document.md
> +- Максимально возможная детализация сражний, акцент на анимации.
тайпо

2024-12-15 09:38 UTC, gochicus commented on docs/gdd/core/game_design_document.md
> +Античность: Герои древнегреческих легенд, например, царь Спарты Леонид или Александр Македонский.
В период Античности славянские племена были ближе к тёмной эпохе. Разрозненные племена, без каких-либо серьёзных бонусов и предпосылок для создания цивилизации.

2024-12-16 14:16 UTC, TorinAsakura requested changes

2024-12-16 14:16 UTC, TorinAsakura commented on docs/gdd/core/game_design_document.md
> +| Лодка/Каноэ       | Лодка/Ладья         | Когг/Барк                      | Фрегат/ Клипер                 | Фрегат/Эсминец                                 | Ракетный фрегат/Безэкипажные катера
в тёмной разве не плоты сперва были? точно лодки?

2024-12-16 14:16 UTC, TorinAsakura commented on docs/gdd/core/game_design_document.md
> +|                   |                     |                                | Воздушный шар                  | Дирижабль/Винтовые самолёты/Реактивная авиация | Реактивная авиация/ Стратосферные корабл
кажется тут необходимо проработка - вынеси в отдельную задачу нам на подумать/поискать

2024-12-16 14:16 UTC, TorinAsakura commented on docs/gdd/core/game_design_document.md
>  |                   | Галера/Триера       | Галера                         | Галера                         |                                                |
не трирема-ли?

2024-12-16 14:16 UTC, TorinAsakura commented on docs/gdd/core/game_design_document.md
> +Миссии Будущего: Построены вокруг освоения космоса с возможной развилкой в сторону подводных просторов.
а тут чиво?

2024-12-16 14:16 UTC, TorinAsakura commented on docs/gdd/core/game_design_document.md
> +- Масштабные сражения: акцент на тактической гибкости и грамотном использовании конфигурации армии, выбранной на основе доступных технологий.
?

2024-12-16 14:22 UTC, gochicus commented on docs/gdd/core/game_design_document.md
> +| Лодка/Каноэ       | Лодка/Ладья         | Когг/Барк                      | Фрегат/ Клипер                 | Фрегат/Эсминец                                 | Ракетный фрегат/Безэкипажные катера
Про лодки точно. Долблёные которые, когда в большом древесном стволе выдалбливается лодка.

2024-12-16 14:23 UTC, gochicus commented on docs/gdd/core/game_design_document.md
>  |                   | Галера/Триера       | Галера                         | Галера                         |                                                |
Триема это латинизированное написание, римское, триера - греческое. По сути корабль один.

2024-12-16 14:24 UTC, gochicus commented on docs/gdd/core/game_design_document.md
> +- Масштабные сражения: акцент на тактической гибкости и грамотном использовании конфигурации армии, выбранной на основе доступных технологий.
Там я ниже развернул.

2024-12-17 10:20 UTC, gochicus commented on docs/gdd/core/game_design_document.md
> +|                   |                     |                                | Воздушный шар                  | Дирижабль/Винтовые самолёты/Реактивная авиация | Реактивная авиация/ Стратосферные корабл
Инициировал задачу: https://github.com/Phoenix-Games-Revolution/last-strategy-docs/issues/24

2024-12-17 22:19 UTC, TorinAsakura approved these changes

2024-12-17 22:20 UTC, merged